<?php
/**
 * @var $block \Unienvios\Cotacao\Block\Adminhtml\OrderEdit\Tab\View
 */
?>
 
<div class="fieldset-wrapper order-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><?php /* @escapeNotVerified */
            echo __('Informações sobre a cotação da Unienvios') ?></span>
    </div>
    <table class="admin__table-secondary">
        <tbody>
        <?php echo $block->getChildHtml(); ?>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Order ID:') ?></th>
            <td><?php echo $block->getOrderIncrementId(); ?></td>
        </tr>
        <tr>
            <th><?php /* @escapeNotVerified */
                echo __('Token:') ?></th>
            <td><?php if(!empty($block->getToken())){
			 echo __('Gerado com sucesso');
			} else{
			echo __('Não existe');
			} ?></td>
        </tr>
	<tr>
            <th><?php /* @escapeNotVerified */
                echo __('Campos adicionais:') ?></th>
            <td><?php echo __('CPF: '); echo $block->getCpf() ?>,
		 <?php echo __('Número da casa: '); echo $block->getNumber() ?>,
		<?php echo __('Bairro: '); echo $block->getNeighbourhood() ?>	
	    	<?php echo __('Complemento: '); echo $block->getComplement() ?>
	    </td>
        </tr>
        </tbody>
    </table>
</div>
